version: '3'

services:
  vdb:
    build:
      context: .
      dockerfile: vdb_docker.df
    ports:
      - "33060:3306"
    expose:
      - "33060"
  vvta:
    build:
      context: .
      dockerfile: vvta_docker.df
    ports:
      - "54320:5432"
    expose:
      - "54320"
  seqrepo:
    build:
      context: .
      dockerfile: vvsr_docker.df
    volumes:
      - seqdata:/usr/local/share/seqrepo
  vv:
    build: .
    depends_on:
      - vdb
      - vvta
    volumes:
      - seqdata:/usr/local/share/seqrepo
      - share:/usr/local/share

volumes:
  share:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${HOME}/variantvalidator_data/share'
  seqdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${HOME}/variantvalidator_data/share/seqrepo'